"""Generate static, accessible pages using only Python's standard library."""
from pathlib import Path
from html import escape
import json

ROOT=Path(__file__).resolve().parents[1]
BASE='https://kley22.github.io/KleytonG.github.io/'
REPO='https://github.com/Kley22/KleytonG.github.io'
LINKEDIN='https://www.linkedin.com/in/kleyton-gon%C3%A7alves-silva/'
PROJECTS=json.loads((ROOT/'content/projects.json').read_text())

def write(path,text):
    dest=ROOT/path
    dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(text,encoding='utf-8')

def head(title,description,path='',prefix='./',demo=False):
    demo_script=f'<script type="module" src="{prefix}assets/js/demos.mjs"></script>' if demo else ''
    return f'''<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#17372e">
<link rel="canonical" href="{BASE+path}"><link rel="icon" href="{prefix}assets/images/favicon.svg" type="image/svg+xml">
<meta property="og:type" content="website"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Kleyton Gonçalves Silva | Portfólio">
<meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(description)}"><meta property="og:url" content="{BASE+path}">
<meta property="og:image" content="{BASE}assets/images/social-preview.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Kleyton Gonçalves Silva — Controle e acompanhamento administrativo: contratos, pagamentos, imóveis e frota">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(title)}"><meta name="twitter:description" content="{escape(description)}"><meta name="twitter:image" content="{BASE}assets/images/social-preview.png">
<link rel="stylesheet" href="{prefix}assets/css/site.css"><script src="{prefix}assets/js/site.js" defer></script>{demo_script}

</head><body><a href="#main" class="skip-link">Ir para o conteúdo</a>'''

def header(prefix='./'):
    return f'''<header class="site-header"><div class="wrap header-inner">
<a class="brand" href="{prefix}" aria-label="Kleyton Gonçalves Silva — início"><span class="brand-mark" aria-hidden="true">K.</span><span>Kleyton Gonçalves<small>Portfólio profissional</small></span></a>
<button class="menu-toggle" aria-expanded="false" aria-controls="navigation" hidden>Menu <span aria-hidden="true">☰</span></button>
<nav class="nav" id="navigation" aria-label="Navegação principal"><a href="{prefix}#projetos">Projetos</a><a href="{prefix}#metodo">Método</a><a href="{prefix}#sobre">Sobre</a><a href="{prefix}#experiencia">Experiência</a><a href="{prefix}#formacao">Formação</a><a class="nav-contact" href="{prefix}#contato">Vamos conversar <span aria-hidden="true">↗</span></a></nav>
</div></header>'''

def footer(prefix='./'):
    return f'''<footer class="site-footer"><div class="wrap footer-inner"><p>© 2026 Kleyton Gonçalves Silva</p><span>Demonstrações com dados de exemplo.</span><a href="{prefix}#main">Voltar ao início ↑</a></div></footer></body></html>'''

def mini(p):
    steps=p['steps'][:3]
    return '<div class="project-cover" aria-hidden="true"><div class="cover-label"><span>'+p['tag']+'</span><span>Explore na prática</span></div><div class="mini-process">'+''.join('<div class="mini-step"><span>'+str(i+1).zfill(2)+'</span><div><strong>'+s['label']+'</strong><small>'+s['title']+'</small></div></div>' for i,s in enumerate(steps))+'</div></div>'

def project_card(p):
    return f'''<article class="project-card" data-category="{p['category']}">{mini(p)}<div class="project-body"><div class="project-type"><span>{p['tag']}</span><span>Case {p['number']}</span></div><h3>{p['title']}</h3><p>{p['short']}</p><div class="project-bottom"><span>Projeto interativo</span><a href="./projetos/{p['slug']}/" aria-label="Abrir projeto: {p['name']}">Abrir projeto</a></div></div></article>'''

def method():
    items=[
      ('bases','Bases de referência','Uma referência comum para os controles.','Cadastros e tabelas auxiliares organizam os vínculos utilizados no dia a dia. Um identificador consistente ajuda a localizar a informação entre diferentes consultas.',['Padronizar os campos de cadastro.','Relacionar os registros por identificadores.','Manter referências fáceis de conferir.'],'Meu foco: organizar e manter as referências do acompanhamento.'),
      ('operacao','Controles operacionais','Cada etapa deixa um registro localizável.','Contratos, documentos, obrigações e lançamentos têm contextos diferentes. O controle preserva essas distinções para apoiar a conferência e o encaminhamento.',['Registrar a competência e o vínculo correto.','Distinguir situação, prazo e documentação.','Acompanhar pendências e atualizações.'],'Meu foco: atualizar, conferir e acompanhar a rotina.'),
      ('paineis','Painéis de acompanhamento','O resumo precisa continuar ligado à origem.','As consultas reúnem informações dos controles. A referência de atualização e o caminho até o registro de origem ajudam a interpretar o que está sendo apresentado.',['Consolidar por finalidade de consulta.','Acompanhar as verificações das bases.','Sinalizar pontos de atenção para os responsáveis.'],'Meu foco: preparar informações claras para apoiar a análise.')]
    controls=''.join(f'<button hidden data-panel="metodo-{key}" aria-controls="metodo-{key}" aria-pressed="false">{i+1:02d} · {label}</button>' for i,(key,label,*_) in enumerate(items))
    panels=''.join(f'<article class="explorer-panel" id="metodo-{key}" aria-labelledby="titulo-{key}"><div class="eyebrow">{label}</div><h3 id="titulo-{key}">{title}</h3><p>{desc}</p><ul class="feature-list">'+''.join(f'<li>{x}</li>' for x in features)+f'</ul><p class="panel-role">{role}</p></article>' for key,label,title,desc,features,role in items)
    return '<section class="section method-section" id="metodo"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Por dentro do controle</div><h2>Da informação<br>ao acompanhamento.</h2></div><p>Três camadas que se complementam. Explore a função de cada uma e como contribuo para a rotina.</p></div><div class="method-explorer" data-explorer><div class="explorer-controls" role="group" aria-label="Explorar as camadas do método">'+controls+'</div><div>'+panels+'</div></div></div></section>'

def home():
    title='Kleyton Gonçalves Silva | Controle e acompanhamento administrativo'
    desc='Portfólio de Kleyton Gonçalves Silva: controle e acompanhamento administrativo de contratos, pagamentos, imóveis e frota. Explore projetos interativos e conheça minha trajetória.'
    out=head(title,desc)+header()
    out+='''<main id="main"><section class="hero"><div class="wrap"><div class="hero-grid"><div><div class="eyebrow">Controle & acompanhamento</div><h1>Kleyton<br><em>Gonçalves Silva.</em></h1><p class="hero-role">Controle e acompanhamento administrativo<br>Contratos · Pagamentos · Imóveis · Frota</p><p class="hero-description">Organizo informações, confiro documentos e acompanho prazos para apoiar o andamento das rotinas administrativas.</p><div class="actions"><a class="button" href="#projetos">Conheça meus projetos <span aria-hidden="true">↗</span></a><a class="button secondary" href="./cv/kleyton-goncalves-silva.pdf?v=20260917-interativo" download>Baixar currículo <span aria-hidden="true">↓</span></a></div><div class="hero-meta"><span><i class="small-dot" aria-hidden="true"></i>Niterói, RJ</span><span>Auxiliar de Escritório · CREA-RJ</span></div></div>
<div class="hero-visual"><div class="method-board"><div class="board-kicker">Meu trabalho, em etapas</div><h2 class="board-title">Organizar.<br>Conferir.<br><em>Acompanhar.</em></h2><ol class="board-flow"><li><span class="flow-number">01</span><div><h3>Informação no lugar certo</h3><p>Cadastros, documentos e referências.</p></div></li><li><span class="flow-number">02</span><div><h3>Detalhes que merecem atenção</h3><p>Vínculos, prazos e pendências.</p></div></li><li><span class="flow-number">03</span><div><h3>Clareza para o próximo passo</h3><p>Consultas e encaminhamentos.</p></div></li></ol><a class="board-footer" href="#metodo">Conheça meu método <span aria-hidden="true">↓</span></a></div></div></div>
<div class="intro-strip"><p>Ferramentas<br>no dia a dia</p><ul><li>Google Planilhas</li><li>Excel</li><li>SEI</li><li>PNCP</li><li>Compras.gov.br</li></ul></div></div></section>
<section class="section projects-section" id="projetos"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Soluções administrativas</div><h2>O controle<br>por trás da rotina.</h2></div><p>Seis projetos para explorar na prática. Experimente filtros, simule cenários e acompanhe as informações que ajudam a organizar cada rotina.</p></div><div class="filter-bar" role="group" aria-label="Filtrar projetos"><button hidden class="filter-button" data-filter="all" aria-pressed="true">Todos os projetos</button><button hidden class="filter-button" data-filter="contratos" aria-pressed="false">Contratos</button><button hidden class="filter-button" data-filter="financeiro" aria-pressed="false">Pagamentos e saldos</button><button hidden class="filter-button" data-filter="operacoes" aria-pressed="false">Frota</button><button hidden class="filter-button" data-filter="paineis" aria-pressed="false">Bases e painéis</button></div><p id="filter-status" class="sr-only" role="status" aria-live="polite"></p><div class="project-grid">'''
    out+=''.join(project_card(p) for p in PROJECTS)
    out+='''</div></div></section>'''+method()+'''
<section class="section about-section" id="sobre"><div class="wrap about-grid"><div><div class="eyebrow">Sobre mim</div><h2>Clareza para acompanhar.<br>Organização para agir.</h2></div><div><p>Sou profissional da área administrativa, com atuação no CREA-RJ no acompanhamento de contratos de obras, facilities e locação de imóveis, acompanhamento de pagamentos e controle operacional de frota.</p><p>Minha rotina reúne conferência de documentos, controle de vigências e saldos, protocolos, notas fiscais e provisões de pagamento. A experiência em licitações e processos administrativos complementa essa visão do trabalho, da informação inicial ao acompanhamento de cada etapa.</p><p class="about-foot">Em formação contínua <span>— Administração e Gestão de Serviços Judiciais</span></p></div></div></section>
<section class="section" id="experiencia"><div class="wrap experience-grid"><div class="sticky-copy"><div class="eyebrow">Experiência profissional</div><h2>Uma trajetória<br>em construção.</h2><p>Da organização documental ao acompanhamento de contratos e pagamentos.</p><div class="actions"><a class="text-link" href="./cv/kleyton-goncalves-silva.pdf?v=20260917-interativo">Ver currículo completo ↗</a></div></div><div class="timeline">
<article class="experience"><div class="experience-head"><h3>CREA-RJ</h3><time>jun/2026 — atual</time></div><p class="role">Auxiliar de Escritório · Tempo integral</p><ul><li>Acompanhamento de contratos de obras, facilities e locação de imóveis, incluindo vigências, renovações, saldos, aditivos e distratos.</li><li>Controle de notas fiscais, provisões de pagamento, contas a pagar e documentação para liquidação de despesas.</li><li>Organização e acompanhamento de protocolos e conferência de certidões fiscais, trabalhistas e documentos de regularidade.</li><li>Atualização de indicadores e planilhas de frota: quilometragem, abastecimento, utilização e manutenções preventivas e corretivas.</li></ul><div class="tags"><span class="tag">Contratos</span><span class="tag">Pagamentos</span><span class="tag">Frota</span></div></article>
<article class="experience"><div class="experience-head"><h3>CREA-RJ</h3><time>ago/2025 — jun/2026</time></div><p class="role">Estagiário Administrativo · Licitações e Contratos (CLIC)</p><ul><li>Pesquisa de preços para contratações públicas com PNCP, Compras.gov.br, editais e mídia especializada.</li><li>Levantamento de valores de mercado e apoio à elaboração de estimativas de preços.</li><li>Apoio à análise de Termos de Referência, especificações técnicas e critérios de contratação.</li></ul><div class="tags"><span class="tag">Pesquisa de preços</span><span class="tag">Contratações públicas</span></div></article>
<article class="experience"><div class="experience-head"><h3>INSS</h3><time>2023 — 2025</time></div><p class="role">Estagiário Administrativo · Perícia Médica</p><ul><li>Abertura, tramitação e acompanhamento de processos administrativos no SEI.</li><li>Organização de processos simultâneos, apoio à instrução de processos previdenciários e encaminhamento entre setores.</li><li>Tratamento de documentos sigilosos conforme as normas institucionais.</li></ul><div class="tags"><span class="tag">SEI</span><span class="tag">Organização documental</span></div></article>
<article class="experience"><div class="experience-head"><h3>ECONIT Engenharia Ambiental</h3><time>jan/2020 — jan/2021</time></div><p class="role">Auxiliar Administrativo</p><ul><li>Controle de folha de ponto, benefícios e documentação de colaboradores.</li><li>Apoio ao recrutamento e seleção: triagem, contato e agendamento.</li></ul></article></div></div></section>
<section class="section skills-section" id="competencias"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Competências & ferramentas</div><h2>O que levo para a rotina.</h2></div><p>Experiência administrativa conectada às ferramentas de organização, consulta e acompanhamento.</p></div><div class="skill-grid"><article class="skill-item"><span class="skill-index">01 / CONTRATOS</span><h3>Prazos e documentação</h3><p>Vigências, renovações, aditivos, distratos, saldos contratuais e organização de documentos.</p></article><article class="skill-item"><span class="skill-index">02 / FINANCEIRO</span><h3>Conferência e acompanhamento</h3><p>Contas a pagar, notas fiscais, provisões, protocolos e documentos para liquidação de despesas.</p></article><article class="skill-item"><span class="skill-index">03 / OPERAÇÃO</span><h3>Processos e controles</h3><p>Indicadores de frota, quilometragem, abastecimento, manutenção, pesquisa de preços e tramitação processual.</p></article></div><div class="tool-list"><span>Ferramentas<br>& plataformas</span><div class="tags">'''
    out+=''.join(f'<span class="tag">{t}</span>' for t in ['Excel','Google Planilhas','Word','Pacote Office','SEI','PNCP','Compras.gov.br','Banco de Preços','Sistemas de gestão financeira'])
    out+='''</div></div></div></section><section class="section education-section" id="formacao"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">Formação & desenvolvimento</div><h2>Aprender faz parte<br>do processo.</h2></div><p>Formação técnica, graduação e cursos complementares ligados à atuação profissional.</p></div><div class="education-layout"><div><article class="degree"><span>Em andamento · Previsão jun/2028</span><h3>Bacharelado em Administração</h3><p>Centro Universitário UNIFATECIE</p></article><article class="degree"><span>Em andamento · Previsão mai/2028</span><h3>Tecnólogo em Gestão de Serviços Judiciais</h3><p>Gran Centro Universitário</p></article><article class="degree"><span>Concluído em 2021</span><h3>Técnico em Administração</h3><p>SENAI</p></article></div><div><h3 class="course-title">Cursos complementares</h3>
<details class="course-group" open><summary>Contratos, licitações e administração pública</summary><ul><li>Programa Gestão Estratégica e Contratos — Escola Virtual.Gov · 365 h</li><li>Nova Lei de Licitações e Contratos Administrativos — Udemy · 15 h</li><li>Licitações e Contratos Administrativos — EV.G/ENAP · 40 h</li><li>Direito Administrativo — EV.G/ENAP · 40 h</li><li>Elaboração de Termos de Referência para Contratação de Bens e Serviços na Nova Lei de Licitações — ENAP · 20 h</li></ul></details>
<details class="course-group"><summary>Inteligência artificial e produtividade</summary><ul><li>Engenharia de Prompt — Gran Faculdade · 30 h · 2026</li><li>Agentes Inteligentes: do Simples ao Avançado — Gran Faculdade · 30 h · 2026</li><li>Inteligência Artificial na Prática: Domine as Ferramentas e Saia na Frente — Gran Faculdade · 30 h · 2026</li></ul></details>
<details class="course-group"><summary>Desenvolvimento profissional</summary><ul><li>Liderança — Gran Faculdade · 30 h · 2026</li><li>Posicionamento Profissional e Empregabilidade — Gran Faculdade · 30 h · 2026</li><li>Performance, Emoções e Relações no Trabalho — Gran Faculdade · 30 h · 2026</li><li>Carreira, Futuro e Protagonismo Profissional — Gran Faculdade · 30 h · 2026</li><li>Educação Financeira - Dinheiro em Movimento — Gran Faculdade · 30 h · 2026</li><li>Nivelamento: Inglês Instrumental — Gran Faculdade · 15 h · 2026</li><li>Nivelamento: Matemática — Gran Faculdade · 15 h · 2026</li></ul></details></div></div></div></section>
<section class="contact" id="contato"><div class="wrap contact-grid"><div><div class="eyebrow">Contato profissional</div><h2>Vamos conversar<br>sobre o próximo passo?</h2><p>Interesse em oportunidades como Auxiliar ou Assistente Administrativo, com foco em controle de contratos, acompanhamento de pagamentos, organização documental e processos administrativos.</p><div class="actions"><a class="button secondary" href="./cv/kleyton-goncalves-silva.pdf?v=20260917-interativo" download>Currículo em PDF <span aria-hidden="true">↓</span></a></div></div><div class="contact-links"><a class="contact-link" href="mailto:kleytons67@gmail.com"><span><small>E-MAIL</small>kleytons67@gmail.com</span><span aria-hidden="true">↗</span></a>'''
    out+=f'''<a class="contact-link" href="{LINKEDIN}"><span><small>REDE PROFISSIONAL</small>LinkedIn</span><span aria-hidden="true">↗</span></a><a class="contact-link" href="https://github.com/Kley22"><span><small>PROJETOS & DOCUMENTAÇÃO</small>GitHub / Kley22</span><span aria-hidden="true">↗</span></a></div></div></section></main>'''
    schema={'@context':'https://schema.org','@type':'Person','name':'Kleyton Gonçalves Silva','url':BASE,'jobTitle':'Auxiliar de Escritório','worksFor':{'@type':'Organization','name':'CREA-RJ'},'sameAs':[LINKEDIN,'https://github.com/Kley22']}
    out+='<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>'+footer()
    write('index.html',out)

def explorer(p):
    controls=''.join(f'<button hidden data-panel="etapa-{i}" aria-controls="etapa-{i}" aria-pressed="false">{i:02d} · {s["label"]}</button>' for i,s in enumerate(p['steps'],1))
    panels=''
    for i,s in enumerate(p['steps'],1):
        panels+=f'<article class="explorer-panel" id="etapa-{i}" aria-labelledby="etapa-titulo-{i}"><div class="eyebrow">Etapa {i:02d}</div><h3 id="etapa-titulo-{i}">{s["title"]}</h3><dl class="scope-list"><div><dt>O que entra</dt><dd>{s["input"]}</dd></div><div><dt>O que faço</dt><dd>{s["action"]}</dd></div><div><dt>O que fica organizado</dt><dd>{s["output"]}</dd></div></dl></article>'
    return '<section class="demo-section" id="fluxo"><div class="demo-heading"><div><div class="eyebrow">Explore as etapas</div><h2>Como o controle funciona.</h2></div></div><div class="workflow-explorer" data-explorer><div class="explorer-controls" role="group" aria-label="Explorar as etapas do controle">'+controls+'</div><div>'+panels+'</div></div></section>'

DEMO_GUIDES={
    'vigencia-contratual':('Os prazos, à vista.','Escolha uma data de referência, filtre a situação e localize os contratos que precisam de atenção.'),
    'previsao-contratual':('Uma previsão para cada cenário.','Ajuste os saldos, os custos mensais e o horizonte para comparar serviços e materiais.'),
    'pagamentos':('Acompanhe cada etapa.','Localize um lançamento, confira a documentação e experimente o acompanhamento de um pagamento.'),
    'controle-imoveis':('Obrigações em um só lugar.','Filtre os imóveis e as despesas para consultar vencimentos, pagamentos e pendências documentais.'),
    'controle-frota':('Conferência que faz diferença.','Calcule o consumo por intervalo de abastecimento e acompanhe a revisão das ocorrências.'),
    'paineis-acompanhamento':('Do registro ao panorama.','Escolha o período e a origem para acompanhar os valores e conferir a composição dos indicadores.')
}

def demo(p):
    title,description=DEMO_GUIDES[p['slug']]
    return f'''<section class="demo-section interactive-section" id="demonstracao" aria-labelledby="demo-title"><div class="demo-heading"><div><div class="eyebrow">Experimente na prática</div><h2 id="demo-title">{title}</h2></div><a class="text-link" href="#fluxo">Entenda as etapas ↓</a></div><p class="demo-intro">{description}</p><div class="demo-app" data-demo="{p['slug']}"><p class="demo-fallback">Para usar os filtros e as simulações, ative o JavaScript. As etapas do projeto estão disponíveis logo abaixo.</p></div></section>'''

def case(p,index):
    prefix='../../'; path=f'projetos/{p["slug"]}/'
    out=head(p['name']+' | Kleyton Gonçalves Silva',p['short'],path,prefix,demo=True)+header(prefix)
    out+=f'''<main id="main"><div class="wrap"><nav class="breadcrumb" aria-label="Caminho da página"><a href="../../#projetos">← Todos os projetos</a></nav><section class="case-hero"><div class="eyebrow">Case {p['number']} / {p['tag']}</div><h1>{p['name']}</h1><p>{p['short']}</p><div class="actions"><a class="button" href="#demonstracao">Experimentar o projeto <span aria-hidden="true">↓</span></a><a class="button secondary" href="#contribuicao">Conheça meu papel</a></div></section><dl class="case-meta"><div><dt>Área de atuação</dt><dd>Controle e acompanhamento administrativo</dd></div><div><dt>Ferramentas da rotina</dt><dd>Google Planilhas · Excel</dd></div><div><dt>Explore o projeto</dt><dd>Filtros, consultas e simulações</dd></div></dl><div class="case-story"><section><div class="eyebrow">O contexto</div><h2>O que precisa de atenção.</h2><p>{p['problem']}</p></section><section><div class="eyebrow">A estrutura</div><h2>Organizar para acompanhar.</h2><p>{p['solution']}</p></section></div><aside class="case-scope" id="contribuicao"><div><div class="eyebrow">Minha contribuição</div><h2>Meu papel no processo.</h2></div><div><p>{p['role']}</p><p>{p['scope']}</p></div></aside>'''
    out+=demo(p)+explorer(p)
    out+=f'''<div class="case-story" id="estrutura"><section><h2>O que o controle reúne</h2><ul class="feature-list">{''.join(f'<li>{x}</li>' for x in p['observed'])}</ul></section><section><h2>Finalidade do controle</h2><p>{p['benefit']}</p></section></div><section class="case-benefit next-steps"><h2>Melhorias propostas</h2><ul class="feature-list">{''.join(f'<li>{x}</li>' for x in p['future'])}</ul></section><section class="case-resources"><h2>Conheça a lógica do projeto.</h2><p>Consulte a documentação para entender os filtros, as premissas dos cálculos e as etapas de acompanhamento.</p><div class="actions"><a class="button secondary" href="{REPO}/blob/main/{path}README.md">Ler a documentação <span aria-hidden="true">↗</span></a><a class="text-link" href="../../#metodo">Como as camadas se conectam ↗</a></div></section>'''
    related=[x for x in PROJECTS if x['slug'] in p['related']]
    out+='<section class="related-projects"><div class="eyebrow">Rotinas conectadas</div><h2>Este controle se conecta a…</h2><div class="actions">'+''.join(f'<a class="button secondary" href="../{r["slug"]}/">{r["title"]} ↗</a>' for r in related)+'</div></section></div>'
    nxt=PROJECTS[(index+1)%len(PROJECTS)]
    out+=f'<aside class="next-project"><div class="wrap"><a href="../{nxt["slug"]}/"><span><small>Próximo case</small>{nxt["title"]}</span><span aria-hidden="true">↗</span></a></div></aside></main>'+footer(prefix)
    write(path+'index.html',out)
    write(path+'README.md',f"# {p['name']}\n\n[Abrir projeto]({BASE+path})\n\n## Contexto\n\n{p['problem']}\n\n## Estrutura\n\n{p['solution']}\n\n## Papel profissional\n\n{p['role']} {p['scope']}\n\n## Demonstração interativa\n\n{DEMO_GUIDES[p['slug']][1]}\n\nOs exemplos foram criados para o portfólio. As interações são executadas no navegador; recarregar a página restaura os valores iniciais.\n\n## Etapas do processo\n\n"+'\n\n'.join(f"### {i}. {s['title']}\n\n- Entrada: {s['input']}\n- Acompanhamento: {s['action']}\n- Saída: {s['output']}" for i,s in enumerate(p['steps'],1))+"\n\n## Recursos do controle\n\n"+'\n'.join('- '+x for x in p['observed'])+"\n\n## Possibilidades de evolução\n\n"+'\n'.join('- '+x for x in p['future'])+"\n")
    write(path+'documentacao/regras.md',f"# Funcionamento\n\n{p['scope']}\n\n{DEMO_GUIDES[p['slug']][1]}\n\nA demonstração usa registros de exemplo e funciona localmente no navegador. Filtros, cálculos e alterações de situação não são persistidos após recarregar a página. As etapas do processo continuam disponíveis sem JavaScript.\n\nAs regras de cada cálculo são apresentadas junto aos seus campos. Os testes dos módulos verificam os cálculos e casos de entrada inválida.\n")

home()
for i,p in enumerate(PROJECTS): case(p,i)
for old,new in [('gestao-frota','controle-frota'),('aditivos-repactuacoes','vigencia-contratual')]:
    path=f'projetos/{old}/'
    dest=next(p for p in PROJECTS if p['slug']==new)
    out=head('Case atualizado | Kleyton Gonçalves Silva','Conheça a versão atualizada deste case.',f'projetos/{new}/','../../')+header('../../')
    out+=f'<main id="main" class="wrap error-page"><div class="eyebrow">Case atualizado</div><h1>{dest["name"]}</h1><p>O conteúdo foi reorganizado para apresentar o processo e o papel de acompanhamento administrativo.</p><div class="actions"><a class="button" href="../{new}/">Conhecer o case atualizado ↗</a></div></main>'+footer('../../')
    write(path+'index.html',out)
write('404.html',head('Página não encontrada | Kleyton Gonçalves Silva','Volte ao portfólio profissional de Kleyton Gonçalves Silva.','404.html','/KleytonG.github.io/')+header('/KleytonG.github.io/')+'<main id="main" class="wrap error-page"><div class="eyebrow">Página não encontrada</div><h1>Vamos retomar<br>o caminho?</h1><p>O endereço pode ter mudado. Você encontra os projetos e a trajetória profissional na página inicial.</p><div class="actions"><a class="button" href="/KleytonG.github.io/">Voltar ao portfólio ↗</a></div></main>'+footer('/KleytonG.github.io/'))
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{BASE+path}</loc></url>' for path in ['']+[f'projetos/{p["slug"]}/' for p in PROJECTS])+'</urlset>\n')
write('robots.txt',f'User-agent: *\nAllow: /\nSitemap: {BASE}sitemap.xml\n')
print('Generated home, six interactive projects, two compatibility pages, documentation, 404 and sitemap.')
